language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install: pip install -r requirements.txt
deploy:
  provider: pypi
  user: '__token__'
  password:
    secure: 'NymHXei8KfLKibAzRsUvNnusYq1zgSERBQhw1Cz5KCg49++Y1mMv7mvTRt0mtlsKeRPEZmeIPsjiMyt6bsNRvgKnENL2QzOnszRSLF7mMTTVhXtc50MYzAe201X2ZX/do6dg48vDDUYBt7JDstkTwdBfPhb+N2R9peVCaATMv1r1Q9amZV+uIqJlQmbGdgu6sm/jZyH3qBVGP0IVGx/hogtgGFsCUc4rmwAAYiP/pvSfg0SpwTjTr/CCyL86cSosP4r2g2lHn8VaH+GmqcEmb5ZqWnptsSZkzLccNsQnYVUBuKeWCeS0WhhgoSg4SEOqILnYfOgv4vqmMsOHheQfCV5phPtY4d9fZeduyBQjXziufh3rIKo8RnTPuZLUH9S4wlacIEGarL3EorbxJt5VmIpxa3oMPBPeXsZlRQXXiMN5TRT+OOz2DdbdF5GjcNv339S4LuywFiDRY0wEzCzBLmxGSEBHDBVtdBpfYGGisvjHlvnx4JaHzx6yTI4/Ekxk96uSL3SVwEXboqs5gLDf8B2TWDphKVK9DA13uMBGmw7GNS9tSrcormkAhVSzhG2hJ2rq+EL+iLO/0I4dlxFAbb3oMQPrYC5Mdmm6HXbEHfc3OuIDqfGFfBwdkCA8a8QrujLPS1reC53hKXWl1TEUe2pg69svZ7SkXYepfirtpO8='
  on:
    tags: true
    branch: master
    python: '3.8'
script:
- python pyAlfawise/__init__.py